site_name: CABINET - DCAN Labs
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - 1. Overview: index.md
  - 2. Coming Soon: comingsoon.md
  - 3. Installation: installation.md
  - 4. Usage: usage.md
  - 5. Participant and Sessions TSV Requirements: participants.md
  - 6. Stages: stages.md
  - 7. Outputs: outputs.md
  - 8. Contributions: contributions.md

