site_name: BIBSnet - DCAN Labs
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - Overview and Workflow: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Outputs: outputs.md
  - Contributions: contributions.md
  - Get Help: help.md

