site_name: BIBSnet - DCAN Labs

theme:
  name: readthedocs
  features:
    - toc.integrate
    - navigation.expand
    - toc.follow
    - navigation.sections
    - header.autohide
    - content.code.annotate  

markdown_extensions:
  - toc:
      permalink: '🔗'

plugins:
  - search

docs_dir: docs

nav:
  - Overview: index.md
  - Installation & Usage: usage.md
  - Outputs: outputs.md
  - Contributions: contributions.md
  - Get Help: help.md

