site_name: BIBSnet - DCAN Labs
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Stages: stages.md
  - Outputs: outputs.md
  - Contributions: contributions.md

